const Question = () => {
  return (
    <div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
      <div>question</div>
    </div>
  );
};

export default Question;
